#!/bin/bash

iterations=10
maindir=$PWD
papidir=/home/nb605/Programs/papi-4.1.0/src
javadir=$PWD/../../java

if [ -f "papiOverheadResults.csv" ];then
rm papiOverheadResults.csv
fi

modes=("clock_thread_cputime_id" "times" "proc" "getrusage") 


j=0
while [ $j -le 3 ];do

../../java/enable_cpu1
mode=${modes[$j]}

cd $papidir
./configure --with-virtualtimer=$mode &> temp
make &> temp

cd $javadir
make clean &> temp
make papirelease &> temp
cd $maindir

../../java/disable_cpu1
sleep 1
i=1
while [ $i -le 10 ];do

echo $mode,`./perftest methods`,`./perftest io` >> papiOverheadResults.csv

i=$((i+1))
done
echo >> papiOverheadResults.csv


j=$((j+1))
done

