#!/bin/bash

VIZSOURCEDIR=$PWD
CLASSESDIR=../../bin
USAGEDIR=/home/nb605/public_html/vtf_viz

cd $CLASSESDIR

if [ -f vtf_viz.jar ];then
	rm vtf_viz.jar
fi

jar cvf vtf_viz.jar vtf_visualizer
cp vtf_viz.jar $VIZSOURCEDIR
cd $VIZSOURCEDIR
jarsigner -storepass vtfkey vtf_viz.jar vtfkey3 -keypass vtfkey

cp vtf_viz.jar $USAGEDIR/
cd $USAGEDIR/

rm -r vtf_visualizer
jar xvf vtf_viz.jar 

cd $PWD
