#!/bin/bash 

source testScripts/preamble

java $parameters -cp bin vtf_tests.ParkTest $parkingthreads 1 &> $tempfile &

sleep $middlesleeping

if [ `ps aux | grep ParkTest | grep -viE grep | awk '{print $2}' | wc -l` -eq 1 ];then
	echo "Failure - Hangs"
	kill -9 `ps aux | grep ParkTest | grep -viE grep | awk '{print $2}'`
else

	if [ `cat $tempfile | grep Assertion | wc -l` -eq 1 ];then
		echo "Failure - `cat $tempfile | grep Assertion`" 
	else

		parking=`cat $tempfile | grep " parking" | wc -l`
		unparking=`cat $tempfile | grep " unparking" | wc -l`
		if [ $parking -eq $unparking ];then
			echo "Success"
			success=1
		else
			echo "Failure parked $parking and unparked $unparking"
		fi
	fi
fi


if [ -z "$success" ];then
echo "java $parameters -cp bin vtf_tests.ParkTest $parkingthreads 1"
fi

