#!/bin/bash

source testScripts/preamble

java $parameters,iothreshold=500000 -cp bin vtf_tests.forwardleap.GenericTest 0 1 0 0 0 1 0 0 0 0 0 0 &> $tempfile &

sleep $sleepingtime
if [ `ps aux | grep GenericTest | grep -viE grep | awk '{print $2}' | wc -l` -eq 1 ];then
	echo "Failure - Hangs"
	kill -9 `ps aux | grep GenericTest | grep -viE grep | awk '{print $2}'`
else

	if [ `cat $tempfile | grep Assertion | wc -l` -eq 1 ];then
		echo "Failure - `cat $tempfile | grep Assertion`" 
	else

		if [ `cat $tempfile | grep "finished" | awk '{print $4}' | awk -F "." '{print $1}'` -ge 10 ];then
			echo "Failure"

		else
			echo "Success"
			success=1
		fi



	fi

fi


if [ -z "$success" ];then
echo "java $parameters,iothreshold=500000 -cp bin vtf_tests.forwardleap.GenericTest 0 1 0 0 0 1 0 0 0 0 0 0"
fi

