#!/bin/bash

source testScripts/preamble

java $parameters -cp bin vtf_tests.JoinTest 1 | awk 'BEGIN{last=0;max=0;}{if ( max < $5-last ) max = ($5 - last);last =$5}END{print 1000*max}' &> $tempfile &

sleep $sleepingtime

if [ `ps aux | grep JoinTest | grep -viE grep | awk '{print $2}' | wc -l` -eq 1 ];then
	echo "Failure - Hangs"
	kill -9 `ps aux | grep JoinTest | grep -viE grep | awk '{print $2}'`
else

	if [ `cat $tempfile | grep Assertion | wc -l` -eq 1 ];then
		echo "Failure - `cat $tempfile | grep Assertion`" 

	else
		if [ `cat $tempfile | awk -F "." '{print $1}'` -gt 125 ];then
			echo "Failure"

		else
			echo "Success"
			success=1
		fi

	fi

fi


if [ -z "$success" ];then
echo "java $parameters -cp bin vtf_tests.JoinTest 1 | awk 'BEGIN{last=0;max=0;}{if ( max < $5-last ) max = ($5 - last);last =$5}END{print 1000*max}'"
fi
