#!/bin/bash 

source testScripts/preamble

#Generic test order: <LLA> <LLI> <LRA> <LRI> <SLA> <SLI> <SRA> <SRI>

testSequence="seq 0 1"

for lla in $($testSequence); do
for lli in $($testSequence); do
for lra in $($testSequence); do
for lri in $($testSequence); do
for sla in $($testSequence); do
for sli in $($testSequence); do
for sra in $($testSequence); do
for sri in $($testSequence); do

conditional=`echo "$lla + $lli + $lra + $lri + $sla + $sli + $sra + $sri" | bc`

if [ $conditional -gt 0 ];then

echo -n modelTimingValidationTest $lla $lli $lra $lri $sla $sli $sra $sri" "
java $parameters -cp bin vtf_tests.forwardleap.ModelTest  $lla $lli $lra $lri $sla $sli $sra $sri &> $tempfile  &

sleep $shortsleeping

if [ `ps aux | grep MonitorTest | grep -viE grep | awk '{print $2}' | wc -l` -eq 1 ];then
	echo "Failure - Hangs"
	kill -9 `ps aux | grep ModelTest | grep -viE grep | awk '{print $2}'`
else

	if [ `cat $tempfile | grep Assertion | wc -l` -eq 1 ];then
		echo "Failure - `cat $tempfile | grep Assertion`" 
	else

		res=`tail -1 $tempfile | awk '{if (NF < 2 || $2 == 0) { print 0; } else {err=($1 - $2)/$2; if (err > 0.1 || err < -0.1) print 0; else print 1;}}'`	
		if [ "$res" = "0" ];then				# 10% error
			echo "Failure"
			cat $tempfile | grep -viE "GDB delay"
		else
			echo "Success"
			success=1
		fi
	fi

fi

if [ -z "$success" ];then
echo "java $parameters -cp bin vtf_tests.forwardleap.ModelTest $lla $lli $lra $lri $sla $sli $sra $sri"
fi

echo "======================================================"
unset success
fi

done
done
done
done
done
done
done
done
