#!/bin/bash 

source testScripts/preamble

java $parameters -cp bin vtf_tests.MulticoreTest 2 &> $tempfile &
maximum_acceptable_result=1.00

sleep $middlesleeping

if [ `ps aux | grep MulticoreTest | grep -viE grep | awk '{print $2}' | wc -l` -eq 1 ];then
	echo "Failure - Hangs"
	kill -9 `ps aux | grep MulticoreTest | grep -viE grep | awk '{print $2}'`
else

	if [ `cat $tempfile | grep Assertion | wc -l` -eq 1 ];then
		echo "Failure - `cat $tempfile | grep Assertion`" 
	else
		success=`echo "$result" | awk '{if ($1 < '$maximum_acceptable_result') print 1;}'`
		if [ $success -eq 1 ];then
			echo "Success"
		else
			echo "Failure"
		fi
	fi

fi


if [ -z "$success" ];then
echo "java $parameters -cp bin vtf_tests.MulticoreTest 2"
fi
