#!/bin/bash 

source testScripts/preamble

java $parameters -cp bin vtf_tests.MonitorTest 2 &> $tempfile &
res=2.00

sleep $shortsleeping

if [ `ps aux | grep MonitorTest | grep -viE grep | awk '{print $2}' | wc -l` -eq 1 ];then
	echo "Failure - Hangs"
	kill -9 `ps aux | grep MonitorTest | grep -viE grep | awk '{print $2}'`
else

	if [ `cat $tempfile | grep Assertion | wc -l` -eq 1 ];then
		echo "Failure - `cat $tempfile | grep Assertion`" 
	else

		success=`cat $tempfile | tail -1 | awk '{err=($1 - '$res')/'$res'; if (err > 0.1 || err < -0.1) print 0; else print 1;}'`
		if [ $success -eq 1 ];then
			echo "Success"
		else
			echo "Failure - `cat $tempfile | tail -1`"
			unset success
		fi
	fi

fi


if [ -z "$success" ];then
echo "java $parameters -cp bin vtf_tests.MonitorTest 2"
fi

