#!/bin/bash

lines=`find . | grep cpp | grep -viE svn | perl -lne 'print "$1.o" if /\.\/(.*)\.cpp/' |wc -l`
i=1

while [ $i -le $lines ];do
filename=`find . | grep cpp | grep -viE svn | perl -lne 'print $1 if /\.\/(.*)\.cpp/' | head -$i | tail -1`
echo "$filename.o: $filename.cpp $filename.h"
echo -e "\t\$(CC) \$(CFLAGS) -c $filename.cpp"
echo

i=$((i+1))
done
