/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class testers_BasicTester */

#ifndef _Included_testers_BasicTester
#define _Included_testers_BasicTester
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     testers_BasicTester
 * Method:    testStringThreadLong
 * Signature: (Ljava/lang/String;Ljava/lang/Thread;J)V
 */
JNIEXPORT void JNICALL Java_testers_BasicTester_testStringThreadLong
  (JNIEnv *, jclass, jstring, jobject, jlong);

/*
 * Class:     testers_BasicTester
 * Method:    testStringThreadObject
 * Signature: (Ljava/lang/String;Ljava/lang/Thread;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_testers_BasicTester_testStringThreadObject
  (JNIEnv *, jclass, jstring, jobject, jobject);

/*
 * Class:     testers_BasicTester
 * Method:    testThreadObject
 * Signature: (Ljava/lang/Thread;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_testers_BasicTester_testThreadObject
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     testers_BasicTester
 * Method:    testThread
 * Signature: (Ljava/lang/Thread;)V
 */
JNIEXPORT void JNICALL Java_testers_BasicTester_testThread
  (JNIEnv *, jclass, jobject);

/*
 * Class:     testers_BasicTester
 * Method:    testObjectLong
 * Signature: (Ljava/lang/Object;J)V
 */
JNIEXPORT void JNICALL Java_testers_BasicTester_testObjectLong
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     testers_BasicTester
 * Method:    testObject
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_testers_BasicTester_testObject
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
