/*
 * JVMStatistics.h
 *
 *  Created on: 11 May 2011
 *      Author: nb605
 */

#ifndef JVMSTATISTICS_H_
#define JVMSTATISTICS_H_

#define JINE_TOTAL_METHODS 49
extern unsigned int jineMethodTransitions[JINE_TOTAL_METHODS][JINE_TOTAL_METHODS];
extern unsigned int jineMethodTransitions_currentMethodCalled;

#ifndef NDEBUG
#define JINE_METHOD_LOG(newMethod) \
		++jineMethodTransitions[jineMethodTransitions_currentMethodCalled][newMethod];	\
		jineMethodTransitions_currentMethodCalled = newMethod;
#else
#define JINE_METHOD_LOG(newMethod) ;
#endif


void initializeJineMethodTransitionsMap();
void printJineMethodTransitionsMap(const char *filename);

#define CALLBACKVMINIT 0
#define RESETPERFORMANCEMEASURES 1
#define WRITEPERFORMANCEMEASURES 2
#define GETTHREADVIRTUALTIME 3
#define GETPAPIREALTIME 4
#define GETTIMEBEFORECREATINGTHREAD 5
#define GETTIMEAFTERCREATINGTHREAD 6
#define LOGJOININGTHREAD 7
#define STARTTIMING 8
#define ENDTIMING 9
#define GETVTFTIME 10
#define GETVTFTIMEINMILLIS 11
#define SETMETHODENTRYDELAY 12
#define SETINTERACTIONPOINTDELAY 13
#define SETTIMEMONITORING 14
#define SETINSTRUMENTATIONTIME 15
#define SIMULATEIODURATION 16
#define ENABLESTACKTRACEMODE 17
#define ONINSTRUMENTATIONSTART 18
#define ONINSTRUMENTATIONEND 19
#define INVALIDATEPROFILINGOF 20
#define REINSTRUMENTRECURSIVEMETHOD 21
#define REGISTERIOINVOCATIONPOINT 22
#define REGISTERMETHOD 23
#define REGISTERMETHODVIRTUALTIME 24
#define REGISTERINTERPRETEDMODE 25
#define REGISTERLOGGERBARRIER 26
#define REGISTERPROFILINGINVALIDATIONPOILCY 27
#define REGISTERTHREAD 28
#define INTERACTIONPOINT 29
#define YIELD  30
#define NOTIFYTIMEDWAITINGTHREADS 31
#define NOTIFYALLTIMEDWAITINGTHREADS 32
#define INTERRUPTONVIRTUALTIMEOUT 33
#define BEFORETHREADINTERRUPT 34
#define REGISTERTHREADBEINGSPAWNED 35
#define SETWAITING 36
#define UNSETWAITING 37
#define CALLBACKTHREADSTART 38
#define CALLBACKMONITORWAIT 39
#define CALLBACKMONITORWAITED 40
#define CALLBACKMONITORCONTENDEDENTER 41
#define CALLBACKMONITORCONTENDEDENTERED 42
#define CALLBACKTHREADEND 43
#define CALLBACKGCSTART 44
#define CALLBACKGCFINISH 45
#define CALLBACKVMDEATH 46
#define REQUESTINGLOCK 47
#define RELEASINGLOCK 48
// After every addition update global count


#endif /* JVMSTATISTICS_H_ */
