/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class virtualtime_EventNotifiervtonly */

#ifndef _Included_virtualtime_EventNotifiervtonly
#define _Included_virtualtime_EventNotifiervtonly
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     virtualtime_EventNotifiervtonly
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_virtualtime_EventNotifiervtonly_init
  (JNIEnv *, jclass);

/*
 * Class:     virtualtime_EventNotifiervtonly
 * Method:    _getThreadVirtualTime
 * Signature: (Ljava/lang/Thread;)J
 */
JNIEXPORT jlong JNICALL Java_virtualtime_EventNotifiervtonly__1getThreadVirtualTime
  (JNIEnv *, jclass);

/*
 * Class:     virtualtime_EventNotifiervtonly
 * Method:    _getPapiRealTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_virtualtime_EventNotifiervtonly__1getPapiRealTime
  (JNIEnv *, jclass);

/*
 * Class:     virtualtime_EventNotifiervtonly
 * Method:    _getJvmtiRealTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_virtualtime_EventNotifiervtonly__1getJvmtiRealTime
  (JNIEnv *, jclass);

/*
 * Class:     virtualtime_EventNotifiervtonly
 * Method:    _getJvmtiVirtualTime
 * Signature: (Ljava/lang/Thread;)J
 */
JNIEXPORT jlong JNICALL Java_virtualtime_EventNotifiervtonly__1getJvmtiVirtualTime
  (JNIEnv *, jclass, jobject);

/*
 * Class:     virtualtime_EventNotifiervtonly
 * Method:    _getElapsedTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_virtualtime_EventNotifiervtonly__1getElapsedTime
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
